# Sylius Resource Configuration
sylius_resource:
    resources:
        three_brs_sylius_404_log_plugin.not_found_log:
            driver: doctrine/orm
            classes:
                model: ThreeBRS\Sylius404LogPlugin\Entity\NotFoundLog
                repository: ThreeBRS\Sylius404LogPlugin\Repository\NotFoundLogRepository

sylius_grid:
    grids:
        three_brs_sylius_admin_404_log_plugin_not_found_log:
            driver:
                name: doctrine/orm
                options:
                    class: ThreeBRS\Sylius404LogPlugin\Entity\NotFoundLog
                    repository:
                        method: createQueryBuilderForGrid
            sorting:
                createdAt: desc
            fields:
                id:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.id
                    sortable: true
                urlDomain:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.url_domain
                    sortable: true
                urlSlug:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.url_slug
                    sortable: true
                queryString:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.query_string
                    sortable: false
                userAgent:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.user_agent
                    sortable: false
                createdAt:
                    type: datetime
                    label: three_brs_sylius_404_log_plugin.ui.created_at
                    sortable: true
                    options:
                        format: 'd.m.Y H:i:s'
            filters:
                urlDomain:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.url_domain
                urlSlug:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.url_slug
                createdAt:
                    type: date
                    label: three_brs_sylius_404_log_plugin.ui.created_at
            actions:
                item:
                    delete:
                        type: delete

        # Grid pro agregované logy
        three_brs_sylius_admin_404_log_plugin_aggregated:
            driver:
                name: three_brs_sylius_404_log_plugin.grid.aggregated_log_data_provider
            fields:
                urlDomain:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.url_domain
                    sortable: true
                urlSlug:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.url_slug
                    sortable: true
                count:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.count
                    sortable: true
                lastOccurrence:
                    type: datetime
                    label: three_brs_sylius_404_log_plugin.ui.last_occurrence
                    sortable: true
                    options:
                        format: 'd.m.Y H:i:s'
            filters:
                urlDomain:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.url_domain
                    options:
                        fields: [urlDomain]
                urlSlug:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.url_slug
                    options:
                        fields: [urlSlug]
                minCount:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.min_count
                    options:
                        fields: [count]
                maxCount:
                    type: string
                    label: three_brs_sylius_404_log_plugin.ui.max_count
                    options:
                        fields: [count]
            actions:
                item:
                    show_details:
                        type: show
                        label: three_brs_sylius_404_log_plugin.ui.show_details
                        options:
                            link:
                                route: three_brs_sylius_404_log_plugin_admin_aggregated_log_details
                                parameters:
                                    domain: resource.urlDomain
                                    slug: resource.urlSlug


# Sylius Fixtures configuration for plugin
sylius_fixtures:
    suites:
        default:
            fixtures:
                three_brs_404_not_found_log:
                    options:
                        amount: 500
                        domains: ['example.com', 'shop.local', 'test.local']
