parameters:
    three_brs_sylius_404_log_plugin.skip_patterns:
        - '/admin'
        - '/api'
        - '/_'

services:
    sylius.repository.three_brs_sylius_404_log_plugin_not_found_log:
        class: ThreeBRS\Sylius404LogPlugin\Repository\NotFoundLogRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - ThreeBRS\Sylius404LogPlugin\Entity\NotFoundLog

    three_brs_sylius_404_log_plugin.grid.aggregated_log_data_provider:
        class: ThreeBRS\Sylius404LogPlugin\Grid\AggregatedLogDataProvider
        arguments:
            $repository: '@sylius.repository.three_brs_sylius_404_log_plugin_not_found_log'
        tags:
            - { name: sylius.grid_driver, alias: three_brs_sylius_404_log_plugin.grid.aggregated_log_data_provider }

    three_brs_sylius_404_log_plugin.controller.aggregated_log_details:
        class: ThreeBRS\Sylius404LogPlugin\Controller\AggregatedLogDetailsController
        arguments:
            $notFoundLogRepository: '@sylius.repository.three_brs_sylius_404_log_plugin_not_found_log'
            $entityManager: '@doctrine.orm.entity_manager'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: controller.service_arguments }

    three_brs_sylius_404_log_plugin.controller.aggregated_log:
        class: ThreeBRS\Sylius404LogPlugin\Controller\AggregatedLogController
        arguments:
            $repository: '@sylius.repository.three_brs_sylius_404_log_plugin_not_found_log'
            $entityManager: '@doctrine.orm.entity_manager'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: controller.service_arguments }

    three_brs_sylius_404_log_plugin.event_listener.exception_logger:
        class: ThreeBRS\Sylius404LogPlugin\EventListener\ExceptionLoggerListener
        arguments:
            $logger: '@logger'
            $entityManager: '@doctrine.orm.entity_manager'
            $notFoundLogFactory: '@three_brs_sylius_404_log_plugin.factory.not_found_log'
            $skipPatterns: '%three_brs_sylius_404_log_plugin.skip_patterns%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -1 }

    three_brs_sylius_404_log_plugin.menu.admin_menu_listener:
        class: ThreeBRS\Sylius404LogPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    three_brs_sylius_404_log_plugin.fixture.not_found_log:
        class: ThreeBRS\Sylius404LogPlugin\Fixture\NotFoundLogFixture
        arguments:
            $manager: '@doctrine.orm.entity_manager'
        tags:
            - { name: sylius_fixtures.fixture }

    # Setono Plugin Detection
    three_brs_sylius_404_log_plugin.service.setono_plugin_detector:
        class: ThreeBRS\Sylius404LogPlugin\Service\SetonoPluginDetector
        arguments:
            $kernel: '@kernel'

    three_brs_sylius_404_log_plugin.twig.setono_plugin_extension:
        class: ThreeBRS\Sylius404LogPlugin\Twig\SetonoPluginExtension
        arguments:
            $pluginDetector: '@three_brs_sylius_404_log_plugin.service.setono_plugin_detector'
        tags:
            - { name: twig.extension }

    # Event Listener for Setono form auto-fill
    three_brs_sylius_404_log_plugin.event_listener.setono_form_script:
        class: ThreeBRS\Sylius404LogPlugin\EventListener\SetonoFormScriptListener
        arguments:
            $channelRepository: '@sylius.repository.channel'
            $twig: '@twig'
        tags:
            - { name: kernel.event_subscriber }

    # Event Listener for auto-deleting 404 logs when redirect is created
    three_brs_sylius_404_log_plugin.event_listener.setono_redirect_created:
        class: ThreeBRS\Sylius404LogPlugin\EventListener\SetonoRedirectCreatedListener
        arguments:
            $notFoundLogRepository: '@sylius.repository.three_brs_sylius_404_log_plugin_not_found_log'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Setono\SyliusRedirectPlugin\Model\Redirect', event: postPersist, method: postPersist }
